package org.apache.iotdb.admin.enums;

public enum IotDBEnum {
    daemon_threads("daemon_threads"),
    live_threads("live_threads"),
    peak_threads("peak_threads"),
    states_threads_new("states_threads_new"),
    states_threads_waiting("states_threads_waiting"),
    states_threads_runnable("states_threads_runnable"),
    states_threads_blocked("states_threads_blocked"),
    states_threads_timed_waiting("states_threads_timed_waiting"),
    states_threads_terminated("states_threads_terminated"),
    gc_pause_count_Failure("gc_pause_count_Failure"),
    gc_pause_count_threshold("gc_pause_count_threshold"),
    gc_pause_total_Failure("gc_pause_total_Failure"),
    gc_pause_total_threshold("gc_pause_total_threshold"),
    g1_humongous_allocation_minor("g1_humongous_allocation_minor"),
    g1_evacuation_pause_minor("g1_evacuation_pause_minor"),
    gclocker_initiated_gc_minor("gclocker_initiated_gc_minor"),
    g1_humongous_allocation_major("g1_humongous_allocation_major"),
    g1_evacuation_pause_major("g1_evacuation_pause_major"),
    gclocker_initiated_gc_major("gclocker_initiated_gc_major"),
    jvm_gc_pause_max_threshold("jvm_gc_pause_max_threshold"),
    jvm_gc_pause_max_failure("jvm_gc_pause_max_failure"),
    gc_pause_max_threshold_major("gc_pause_max_threshold_major"),
    gc_pause_max_threshold_minor("gc_pause_max_threshold_minor"),
    gc_pause_max_failure_minor("gc_pause_max_failure_minor"),
    gc_pause_count_threshold_major("gc_pause_count_threshold_major"),
    gc_pause_count_failure_minor("gc_pause_count_failure_minor"),
    gc_pause_total_failure_minor("gc_pause_total_failure_minor"),
    jvm_gc_memory_promoted("jvm_gc_memory_promoted"),
    jvm_gc_max_data_size("jvm_gc_max_data_size"),
    jvm_gc_live_data_size("jvm_gc_live_data_size"),
    jvm_threads_live_threads("jvm_threads_live_threads"),
    jvm_gc_memory_allocated("jvm_gc_memory_allocated"),
    jvm_gc_overhead("jvm_gc_overhead"),
    jvm_buffer_memory_used_mapped("jvm_buffer_memory_used_mapped"),
    jvm_buffer_memory_used_direct("jvm_buffer_memory_used_direct"),
    jvm_buffer_total_capacity_mapped("jvm_buffer_total_capacity_mapped"),
    jvm_buffer_total_capacity_direct("jvm_buffer_total_capacity_direct"),
    jvm_buffer_count_mapped("jvm_buffer_count_mapped"),
    jvm_buffer_count_direct("jvm_buffer_count_direct"),
    jvm_memory_committed_class_space("jvm_memory_committed_class_space"),
    jvm_memory_committed_code_cache("jvm_memory_committed_code_cache"),
    jvm_memory_committed_metaspace("jvm_memory_committed_metaspace"),
    jvm_memory_committed_old_gen("jvm_memory_committed_old_gen"),
    jvm_memory_committed_eden_space("jvm_memory_committed_eden_space"),
    jvm_memory_committed_survivor_space("jvm_memory_committed_survivor_space"),
    jvm_memory_max_class_space("jvm_memory_max_class_space"),
    jvm_memory_max_code_cache("jvm_memory_max_code_cache"),
    jvm_memory_max_metaspace("jvm_memory_max_metaspace"),
    jvm_memory_max_old_gen("jvm_memory_max_old_gen"),
    jvm_memory_max_eden_space("jvm_memory_max_eden_space"),
    jvm_memory_max_survivor_space("jvm_memory_max_survivor_space"),
    jvm_memory_used_class_space("jvm_memory_used_class_space"),
    jvm_memory_used_code_cache("jvm_memory_used_code_cache"),
    jvm_memory_used_metaspace("jvm_memory_used_metaspace"),
    jvm_memory_used_old_gen("jvm_memory_used_old_gen"),
    jvm_memory_used_eden_space("jvm_memory_used_eden_space"),
    jvm_memory_used_survivor_space("jvm_memory_used_survivor_space"),
    jvm_classes_unloaded("jvm_classes_unloaded"),
    jvm_classes_loaded("jvm_classes_loaded"),
    jvm_compilation_time("jvm_compilation_time"),
    sys_cpu_load("sys_cpu_load"),
    sys_cpu_cores("sys_cpu_cores"),
    process_cpu_time("process_cpu_time"),
    sys_total_physical_memory_size("sys_total_physical_memory_size"),
    process_mem_ratio("process_mem_ratio"),
    process_used_mem("process_used_mem"),
    sys_disk_total_space("sys_disk_total_space"),
    sys_disk_free_space("sys_disk_free_space"),
    file_count_wal("file_count_wal"),
    file_size_wal("file_size_wal"),
    file_count_seq("file_count_seq"),
    file_size_seq("file_size_seq"),
    file_count_unseq("file_count_unseq"),
    file_size_unseq("file_size_unseq"),
    entry_total_closeOperation("entry_total_closeOperation"),
    entry_total_executeQueryStatement("entry_total_executeQueryStatement"),
    entry_total_executeStatement("entry_total_executeStatement"),
    entry_total_getProperties("entry_total_getProperties"),
    entry_total_insertRecord("entry_total_insertRecord"),
    entry_total_closeSession("entry_total_closeSession"),
    entry_total_openSession("entry_total_openSession"),
    entry_total_requestStatementId("entry_total_requestStatementId"),
    entry_total_fetchResults("entry_total_fetchResults"),
    entry_total_set_storage_group("entry_total_set_storage_group"),
    entry_mean_closeOperation("entry_mean_closeOperation"),
    entry_mean_executeQueryStatement("entry_mean_executeQueryStatement"),
    entry_mean_executeStatement("entry_mean_executeStatement"),
    entry_mean_getProperties("entry_mean_getProperties"),
    entry_mean_insertRecord("entry_mean_insertRecord"),
    entry_mean_closeSession("entry_mean_closeSession"),
    entry_mean_openSession("entry_mean_openSession"),
    entry_mean_requestStatementId("entry_mean_requestStatementId"),
    entry_mean_fetchResults("entry_mean_fetchResults"),
    entry_mean_set_storage_group("entry_mean_set_storage_group"),
    entry_count_closeOperation("entry_count_closeOperation"),
    entry_count_executeQueryStatement("entry_count_executeQueryStatement"),
    entry_count_executeStatement("entry_count_executeStatement"),
    entry_count_getProperties("entry_count_getProperties"),
    entry_count_insertRecord("entry_count_insertRecord"),
    entry_count_closeSession("entry_count_closeSession"),
    entry_count_openSession("entry_count_openSession"),
    entry_count_requestStatementId("entry_count_requestStatementId"),
    entry_count_fetchResults("entry_count_fetchResults"),
    entry_count_set_storage_group("entry_count_set_storage_group"),
    gc_pause_total_threshold_major("gc_pause_total_threshold_major");

    private String key;

    IotDBEnum(String k) {
        this.key = k;
    }


    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }
}

